os:
  - linux
  - osx

dist: trusty
osx_image: xcode10

sudo: required
language: python
python: "3.6"

install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo tools/development_image/install_deps_linux.sh; fi   
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then tools/development_image/install_deps_darwin.sh; fi   

script:
  - pip3 wheel .
