environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.8"
      PYTHON_ARCH: "64"

install:
  - powershell -ExecutionPolicy Bypass -File %APPVEYOR_BUILD_FOLDER%\tools\development_image\install_deps_windows.ps1
  - ps: "ls \"C:/flatbuffers\""
  - set PATH=C:\flatbuffers;C:\Python36-x64;C:\Python36-x64\scripts;%PATH%
  - echo %PATH%
  - python --version

build_script:
  - python --version
  - pip --version
  - pip install wheel
  - pip wheel %APPVEYOR_BUILD_FOLDER%
