environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.8"
      PYTHON_ARCH: "64"

install:
  - powershell -File %APPVEYOR_BUILD_FOLDER%\tools\development_image\install_deps_windows.ps1
  - set PATH=C:\Python36-x64;C:\Python36-x64\scripts;C:\Libraries\boost_1_67_0;C:\flatbuffers;%PATH%
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive

build_script:
  - powershell -File %APPVEYOR_BUILD_FOLDER%\tools\development_image\build.ps1
